# -*- coding: utf-8 -*-
"""숫자 카드 게임.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zlMHk8RlFCxlHT7FOJtW6Q2LJCJoo1Gd
"""

# n행 m열 입력
n, m = map(int, input().split())

li_min = []

for i in range(n):
    li = list(map(int,input().split())) # 각 행마다 숫자 입력
    li_min.append(min(li)) # 각 행마다 가장 작은 숫자 찾기

print(max(li_min)) # 행마다 가장 작은 숫자가 들어있는 list에서 가장 큰 값 출력