# -*- coding: utf-8 -*-
"""큰 수의 법칙.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zlMHk8RlFCxlHT7FOJtW6Q2LJCJoo1Gd
"""

n, k, m = map(int, input().split())
li = list(map(int, input().split()))

li.sort()

first = li[n-1] # 가장 큰 수
second = li[n-2] # 두 번째로 큰 수

# 가장 큰 수가 더해지는 횟수 계산
count = int(m / (k+1))*k + m % (k+1)

result = 0
result+= count* first + (m-count)*second
print(result)